<?php


use PHPUnit\Framework\TestCase;

class ChampionTest extends TestCase
{
    public function test_champion_can_take_damage()
    {
        $this->assertInstanceOf(\App\Models\Champion::class, $this->cwel);
        $this->assertEquals(100, $this->cwel->baseHp);
        $this->assertEquals(100, $this->cwel->actualHp);
        $this->cwel->receivePhysicalDamage(150);
        $this->assertEquals(100, $this->cwel->baseHp);
        $this->assertEquals(50, $this->cwel->actualHp);
    }
    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub
        try{
            $this->db = new PDO("mysql:host=localhost;dbname=lelek", 'baza', '1234');
            $this->db->setAttribute(PDO::ATTR_ERRMODE, PDO::ERRMODE_EXCEPTION);
//    echo "Connected successfully";
        } catch(PDOException $e) {
            echo "Connection failed: " . $e->getMessage();
        }
        $this->cwel = \App\Models\Champion::addNew($this->db, 'cwel', 100, 200);
    }
}
